name: 'api_logs_dbt'
version: '1.0.0'
config-version: 2

profile: 'api_logs_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  api_logs_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  api_logs_dbt:
    +schema: gold_dbt
